#!/bin/sh

/bin/chown -R root:root /usr/share/config-puppet-manifests
find /usr/share/config-puppet-manifests -type d | xargs -P 1 -L 1 chmod 700
find /usr/share/config-puppet-manifests -type f | xargs -P 1 -L 1 chmod 600

if [ -e /etc/puppet ] ; then
    rm -rvf /etc/puppet
fi

ln -s /usr/share/config-puppet-manifests /etc/puppet
